{
  "0 debug pnpm:scope": {
    "selected": 1,
    "workspacePrefix": "/Users/sandibekibraimov/Dev/monorepotest"
  },
  "1 info pnpm": {
    "err": {
      "name": "Error",
      "message": "Command failed with ENOENT: create next-app external-docs --typescript\nspawn create ENOENT",
      "code": "ENOENT",
      "stack": "Error: Command failed with ENOENT: create next-app external-docs --typescript\nspawn create ENOENT\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)\n    at onErrorNT (node:internal/child_process:478:16)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
    }
  },
  "2 error pnpm": {
    "errno": -2,
    "code": "ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL",
    "syscall": "spawn create",
    "path": "create",
    "spawnargs": [
      "next-app",
      "external-docs",
      "--typescript"
    ],
    "originalMessage": "spawn create ENOENT",
    "shortMessage": "Command failed with ENOENT: create next-app external-docs --typescript\nspawn create ENOENT",
    "command": "create next-app external-docs --typescript",
    "escapedCommand": "create next-app external-docs --typescript",
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "killed": false,
    "prefix": "/Users/sandibekibraimov/Dev/monorepotest",
    "err": {
      "name": "Error",
      "message": "Command failed with ENOENT: create next-app external-docs --typescript\nspawn create ENOENT",
      "code": "ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL",
      "stack": "Error: Command failed with ENOENT: create next-app external-docs --typescript\nspawn create ENOENT\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)\n    at onErrorNT (node:internal/child_process:478:16)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
    }
  }
}